[TRAIN_FEATURES]
TRAIN_FEATURES =['CUSTOMER_TYPE',
    'up_to_18',
    '18_to_30',
    '30_to_45',
    'after_45',
    'GENDER',
    'MARITAL_STATUS',
    'COUNTRY',
    'BLACK_LIST_FLG',
    'CHILDREN_CNT',
    'VIP_FLG',
    'IS_EMPLOYEE',
    'CUSTOMER_TRANSACTIONS_CNT',
    'CUSTOMER_TRANSACTIONS_SUM',
    'CREDIT_FLG',
    'CARDS_CNT',
    'CONTRACT_STATUS (text)',
    'CONTRACT_TYPE (text)',
    'CREDIT_CLASS (text)',
    'MEAN_LOAN_AMT_x',
    'MEAN_TRANSACTION_x',
    'TRANSACTION_TO_BALANCE_RATIO',
    'TRANSACTION_TO_LOAN_RATIO'
]
CATEGORICAL_COLUMNS = [
    'CUSTOMER_TYPE',
    'GENDER', 
    'MARITAL_STATUS', 
    'COUNTRY', 
    'CONTRACT_STATUS (text)', 
    'CONTRACT_TYPE (text)', 
    'CREDIT_CLASS (text)'
]